### ISSUE TITLE
To Include the Tic Tac Toe Game 

### ISSUE THREAD

**Issue by MithanshuHedau** [divyansh-2005/GAME_PLAYER#101]
**Tic Tac Toe Game**
I'm always frustrated when my Tic-Tac-Toe game lacks engaging visuals and smooth transitions, making it feel static and unexciting. I want to create a more interactive experience that captures players' attention and makes the game enjoyable to play

**Description & features**
I'm looking to improve the Tic-Tac-Toe game by adding engaging visuals and smooth transitions for a more interactive experience. Key features to implement include:

🟢Animations for winning moves and transitions.
🟢A responsive layout for mobile devices.
🟢Score tracking across multiple rounds.
🟢Options for single-player and two-player modes.
🟢These enhancements will make the game more enjoyable and visually appealing for players.

**Screen Shot/ Demo video**
![image](https://github.com/user-attachments/assets/c34fdbf0-6118-4f51-839b-702afabd5201)

**check list**
- [✔️ ] I am contributing under GSSoC-ext
- [✔️ ] I am contributing under hacktoberfest
- [✔️] I follow contribution guidlines

**Comment by zalabhavy** [comment]
duplicate issue of #97
