### ISSUE TITLE
[FEATURE] Add contact form

### ISSUE THREAD

**Issue by ayushrana83** [divyansh-2005/GAME_PLAYER#114]
- add a contact form . So user can give feedbacks or any message.
- assign me this feature
![contact](https://github.com/user-attachments/assets/745c6905-3e9f-4535-9be8-00617624ac65)

**Comment by Rohit916214** [comment]
@divyansh-2005 can you assign to me?

**Comment by zalabhavy** [comment]
No need now @ayushrana83 find another issue !
