### ISSUE TITLE
[FEATURE]: User Authentication Feature

### ISSUE THREAD

**Issue by VertikaBajpai** [divyansh-2005/GAME_PLAYER#128]
**Is your feature request related to a problem? Please describe.**
Add a SignUp/Login feature for user identification and tracking user details like most played games

**Describe the solution you'd like**
It will be a Password-based Authentication where user credentials like name, email and password will be required

**Screenshots**
![image](https://github.com/user-attachments/assets/dc94c564-2275-43e2-8247-8b813d104696)
![image](https://github.com/user-attachments/assets/b1385406-ecfe-4a5d-bc0c-4f4aae9f2bf9)

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Comment by zalabhavy** [comment]
Not need now you can work on another issue !
