### ISSUE TITLE
[BUG] About and Contact Page 

### ISSUE THREAD

**Issue by souvikpramanikgit** [divyansh-2005/GAME_PLAYER#132]
**Describe the bug**
When i go on the about and contact page, the pages doesn't cover the whole page.

**Expected behavior**
I wanted to do it full page.

**Screenshots before**
![image](https://github.com/user-attachments/assets/4081419c-188e-4131-9afe-ee1a66158b56)
![image](https://github.com/user-attachments/assets/a8504e52-eb53-48cd-9224-0e6af399b819)

**screenshots after fix***
![image](https://github.com/user-attachments/assets/927c86d2-93cd-4043-a82d-6ada7362503d)
![image](https://github.com/user-attachments/assets/57e8ac4a-854c-48e8-9109-eb61308f31ee)

**check list**
- [ Yes] I am contributing under GSSoC-ext
- [ Yes] I am contributing under hacktoberfest
- [ Yes] I follow contribution guidlines

**Additional context**
I also find another bug which i write in another issue(responsive navbar)

**Comment by zalabhavy** [comment]
@souvikpramanikgit Do it !
