### ISSUE TITLE
[FEATURE] Add Cursor Animation and Improve Button Styles with Animation on the Games Platform

### ISSUE THREAD

**Issue by Sancharisingh** [divyansh-2005/GAME_PLAYER#140]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the user interface of the Games Platform feels static, which impacts user engagement. The lack of dynamic interactions, especially in cursor movement and button styles, makes the platform less appealing to the end users.
**Describe the solution you'd like**
I propose adding an animation effect to the cursor, so it creates a more engaging experience when users navigate the platform. Additionally, I'd like to improve the button styles by introducing hover animations and better text alignment. These changes would make the platform more visually dynamic and interactive, contributing to a smoother, more enjoyable user experience.

This feature will enhance the aesthetic and interactivity of the platform, providing a richer and more immersive experience for users.

**check list**
- [ yes] I am contributing under GSSoC-ext
- [ yes] I am contributing under hacktoberfest
- [ yes] I follow contribution guidlines

**Comment by biswajit-sarkar-007** [comment]
Hi @Sancharisingh ,

I see that this issue is open and would love to work on it. Could you please assign it to me?

Thank you!

**Comment by zalabhavy** [comment]
@Sancharisingh Go ahead make animation that matches the theme of website
