### ISSUE TITLE
Add a contact us form with backend on the contact us page 

### ISSUE THREAD

**Issue by AyushSharma72** [divyansh-2005/GAME_PLAYER#151]
**Is your feature request related to a problem? Please describe.**
there is no contact us form i will add a contact us form on the contact us page 
and also add backend by which user can send you email 

![image](https://github.com/user-attachments/assets/2bf5ccdb-7bfc-491e-98a4-a8a199aaea3f)

please assign this issue to me @divyansh-2005 

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Comment by zalabhavy** [comment]
Not need now thank you for issue you can work on another issue.

**Comment by AyushSharma72** [comment]
> Not need now thank you for issue you can work on another issue.

give me some issue @divyansh-2005
