### ISSUE TITLE
Want to add Tic-Tac-Toe game

### ISSUE THREAD

**Issue by Suvadip-sana** [divyansh-2005/GAME_PLAYER#155]
**Name of Game**
Tic-Tac-Toe
**Description & features**
A standard tic tac toe game, Where also available checking for draw  
**Screen Shot/ Demo video**

**Additional context**
![image](https://github.com/user-attachments/assets/585c2434-2b5e-4119-a14b-2571e472092a)
![image](https://github.com/user-attachments/assets/b3f25d72-30bd-4986-a00b-0601efa0d98e)
![image](https://github.com/user-attachments/assets/b12235de-2681-4fc2-a7fd-a9c2a6724c95)

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Comment by Riyachauhan11** [comment]
@divyansh-2005 I'd like to work on this, if @Suvadip-sana hasn't already started. Please let me know if it's available!
