### ISSUE TITLE
Lights Out Game

### ISSUE THREAD

**Issue by samriddhitiwary** [divyansh-2005/GAME_PLAYER#156]
**Name of Game**
Lights Out Game

**Description & features**
Lights Out is a simple yet engaging puzzle game designed for two players. The objective is to turn off all the lights on a 5x5 grid. Each cell in the grid can either be "on" (lit) or "off" (unlit). When a player clicks on a cell, that cell and its adjacent neighbors (up, down, left, right) toggle their states. The game requires strategic thinking and planning to achieve the goal of turning off all the lights.

**check list**
- [ x] I am contributing under GSSoC-ext
- [x ] I am contributing under hacktoberfest
- [x ] I follow contribution guidlines

**Comment by zalabhavy** [comment]
@samriddhitiwary Without assign you cant make any PR.

**Comment by samriddhitiwary** [comment]
@divyansh-2005 Oh I am sorry

**Comment by samriddhitiwary** [comment]
@divyansh-2005 Than can you please assign this to me?

**Comment by samriddhitiwary** [comment]
@divyansh-2005 Or can you please tell me how to procced with it, should I create the issue again and the raise the PR?
I am sorry I did'nt know about it, and I really want to merge these two games
