### ISSUE TITLE
[BUG] In Home page, top 4 games out of screen when adding a new game 

### ISSUE THREAD

**Issue by mehul-m-prajapati** [divyansh-2005/GAME_PLAYER#164]
**Describe the bug**
 In Home page, top 4 games out of screen when adding a new game 

**To Reproduce**
1. Go to GameSection.jsx
2. Add test code
```
    {
        name: "test",
        description:
          "test",
        link: "/test",
      },
```
4. Scroll down to home page
5. See the error

**Expected behavior**
All games should be visible

**Screenshots before**
![s1](https://github.com/user-attachments/assets/a9f273cf-9998-40df-b610-a96e62ba1022)

**screenshots after fix***

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Additional context**
n/a

**Comment by zalabhavy** [comment]
That is not actual issue that is created by your PR deployment so I not merge that PR.
