### ISSUE TITLE
[FEATURE] Add Chatbot 

### ISSUE THREAD

**Issue by NK-Works** [divyansh-2005/GAME_PLAYER#179]
I want to implement a chatbot for the website.

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Comment by govindumeesala** [comment]
@zalabhavy  
#47  is already present . 
I will work on it and submit pr today.

**Comment by NK-Works** [comment]
@divyansh-2005 @zalabhavy can you please merge my pr its been a month and now the event will close tomorrow.
