### ISSUE TITLE
Change the favicon

### ISSUE THREAD

**Issue by KrishChothani** [divyansh-2005/GAME_PLAYER#191]
**Is your feature request related to a problem? Please describe.**
Change the Favicon

**Describe the solution you'd like**
change favicon on web-browser --->>> default  to TeleGames's logo

**screenshots/video of feature**
![Image](https://github.com/user-attachments/assets/ede85c3f-ab7f-4649-9554-cc7c323a8315)

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Comment by zalabhavy** [comment]
@KrishChothani Already done !
