### ISSUE TITLE
Adding about and contact page

### ISSUE THREAD

**Issue by Gauravtb2253** [divyansh-2005/GAME_PLAYER#2]
Hello I would like to add about page and contact page to the website
Pls assign this to me

Thank you

**Comment by divyansh-2005** [comment]
@Gauravtb2253  go ahead

**Comment by Gauravtb2253** [comment]
also add hacktoberfest label pls

**Comment by Swadeeppatil** [comment]
hello 
i would like to add contact & login peg  in website
@Gauravtb2253  assign me this task under hacktoberfest2024
