### ISSUE TITLE
Search Games Title Alignment 

### ISSUE THREAD

**Issue by MithanshuHedau** [divyansh-2005/GAME_PLAYER#21]
Though the Landing page is good but the title of Search Games is not aliging with that . 

Making the  alignment proper of text  " Search Games " and size of it 
![image](https://github.com/user-attachments/assets/54c33f34-cb49-4235-8d80-08b8fc6083ce)

**check list**
- [✔] I am contributing under GSSoC-ext
- [✔] I am contributing under hacktoberfest
- [✔] I follow contribution guidlines

**Comment by zalabhavy** [comment]
@MithanshuHedau Go ahead.
