### ISSUE TITLE
Click Speed Test game

### ISSUE THREAD

**Issue by govindumeesala** [divyansh-2005/GAME_PLAYER#211]
**Name of Game**
Click speed test game

**Description & features**
- Description: The player must click as many times as possible within a set amount of time (e.g., 10 seconds).
### Key Concepts:
- Use of setInterval for countdown timer.
- State for tracking the number of clicks and timer.
- Display of score and option to restart.

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

@zalabhavy  please assign me this

**Comment by RaiDevX8** [comment]
#108

**Comment by govindumeesala** [comment]
> #108

This is diff from the game u proposed. Read the description.
