### ISSUE TITLE
[FEATURE] : Separate Home Page for GAME_PLAYER

### ISSUE THREAD

**Issue by IkkiOcean** [divyansh-2005/GAME_PLAYER#219]
### Issue: Separate Home Page for `GAME_PLAYER`

**Description:**
The current home page and the game page look very similar, which causes confusion for the users. To enhance user experience, a distinct home page will be created for the `GAME_PLAYER`.

**Proposed Changes:**
- Add a hero section to the home page.
- Revamp the overall look of the home page to make it visually distinct from the game page.
- Ensure that the navigation from the home page to the game page is clear and intuitive.

**Tasks:**
1. Design a new hero section for the home page.
2. Update the home page layout and styling.
3. Ensure consistent branding across both pages.
4. Test the user flow from home page to the game page.

**Expected Outcome:**
A distinct, user-friendly home page that sets the stage for the game and improves the overall user experience.

## Screenshots
<img width="1276" alt="Screenshot 2024-10-14 at 11 44 42 AM" src="https://github.com/user-attachments/assets/6405a40c-0c82-4ccc-8b82-8076436e2f72">

<img width="1280" alt="Screenshot 2024-10-14 at 11 44 33 AM" src="https://github.com/user-attachments/assets/6277fb2b-0d45-4284-9176-4b7c11fb9d55">

They both look so similiar

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Comment by zalabhavy** [comment]
@IkkiOcean Not need to make separate page now.
