### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by krishpathak** [divyansh-2005/GAME_PLAYER#24]
**Describe the bug**
Font-size is so small it is not properly visible.

**To Reproduce**
Change the font size at various places.

**Expected behavior**
Enhance UI

**Screenshots before**
![image](https://github.com/user-attachments/assets/ae02f783-541f-40d4-98b8-a58f859a4143)

**screenshots after fix***
![image](https://github.com/user-attachments/assets/d0c715b2-3858-49a7-9eeb-7fc4bfbf4ad8)

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Comment by zalabhavy** [comment]
@krishpathak Go ahead.

**Comment by krishpathak** [comment]
@zalabhavy Can u please label hacktoberfest?
