### ISSUE TITLE
[BUG] Remove Node Modules File

### ISSUE THREAD

**Issue by souvikpramanikgit** [divyansh-2005/GAME_PLAYER#250]
**Describe the bug**
Remove Node Modules File, as the file size is big, it's take time to clone it, so for this i think it will be better to remove the node modules.

**Screenshots before**
![image](https://github.com/user-attachments/assets/0bf26d58-4746-47cc-8b6d-6a82a773b533)

**check list**
- [Y] I am contributing under GSSoC-ext
- [Y] I am contributing under hacktoberfest
- [Y] I follow contribution guidlines

**Comment by AkshatSharma5** [comment]
@souvikpramanikgit  Please assign me this issue
[X] I am contributing under GSSoC-ext
[X] I am contributing under hacktoberfest
[X] I follow contribution guidlines
