### ISSUE TITLE
[FEATURE] Aligning the games card to the centre 

### ISSUE THREAD

**Issue by HemantBatra873** [divyansh-2005/GAME_PLAYER#257]
**Is your feature request related to a problem? Please describe.**
Yes , the problem is that the game cards are all aligned towards the left they should be evenly aligned over the entire width of the screen .

**Describe the solution you'd like**
In the pc mode . The games-container is not taking up the entire width and that's why on a particular width the games look that they are weirdly put in the container . But I know how to fix these kind of issues please assign it to me under hacktoberfest-accepted and gssoc-ext .

**Screenshots**

![telegames issue](https://github.com/user-attachments/assets/27dbfb9c-da47-4052-a7f5-67b5cf51650f)

![telegames issue 2](https://github.com/user-attachments/assets/f61ff4ba-1c4d-4039-baba-b3a1d6db4437)

![telegames 3](https://github.com/user-attachments/assets/1290916e-8dea-441a-adad-0846d2d34d56)

**check list**
- [Yes] I am contributing under GSSoC-ext
- [Yes] I am contributing under hacktoberfest
- [Yes] I follow contribution guidlines

**Comment by zalabhavy** [comment]
@HemantBatra873 Everything is ok !
