### ISSUE TITLE
Changing th Favicon 

### ISSUE THREAD

**Issue by MithanshuHedau** [divyansh-2005/GAME_PLAYER#26]
changing the favicon of the website 

**Screenshots**
![image](https://github.com/user-attachments/assets/a6d54d45-a48e-485d-9a4d-a786255d403e)

**check list**
- [ ✔] I am contributing under GSSoC-ext
- [✔ ] I am contributing under hacktoberfest
- [✔ ] I follow contribution guidlines

**Comment by divyansh-2005** [comment]
Duplicate issue #9
