### ISSUE TITLE
Add new Game :: Realm Rush

### ISSUE THREAD

**Issue by KrishChothani** [divyansh-2005/GAME_PLAYER#265]
# **Realm Rush**

**Overview:**  
Realm Rush is a Unity-based game where players protect their gold inventory from enemies by building defensive structures that attack the intruders. This 2D card-board game with a 3D perspective involves strategic planning and quick decisions to fend off enemy attacks.

**Game Mechanics:**
- **Defense Building:** Players construct buildings that automatically attack enemies attempting to steal gold.
- **Enemy Waves:** Waves of enemies try to steal gold, and players must strategize their defenses to prevent the theft.
- **Game Progression:** Players must survive increasingly difficult waves of enemies while managing resources to build stronger defenses.

**Screenshot/Demo:**  
![Game Preview](https://github.com/user-attachments/assets/5e14989e-f813-4d2a-8829-1352f2162faa)

**Additional Context:**  
Realm Rush combines strategic base-building with action-packed enemy encounters, challenging players to outsmart and outlast their opponents. The game's mix of planning and fast-paced gameplay provides a rewarding experience for both casual and experienced players.

**Check List:**
- [X] I am contributing under GSSoC-ext
- [X] I am contributing under Hacktoberfest
- [X] I follow contribution guidelines

**Comment by zalabhavy** [comment]
@KrishChothani Without Assignment Why you are making PR.

**Comment by KrishChothani** [comment]
sorry for that , can you reopen this any assign me ?
