### ISSUE TITLE
adding a contributors page.

### ISSUE THREAD

**Issue by vidhi-github** [divyansh-2005/GAME_PLAYER#285]
**Name of Game**
I would like to add a contributors page to this website.

kindly assign me this issue under gssoc-ext and hacktoberfest-accepted under good level.

**Description & features**
separate API's and page would be there.

**Screen Shot/ Demo video**

**Additional context**

**check list**
- [ #] I am contributing under GSSoC-ext
- [# ] I am contributing under hacktoberfest
- [ #] I follow contribution guidlines

**Comment by vidhi-github** [comment]
U can continue with it.

**Comment by akash70629** [comment]
> @akash70629 U can continue with it.

Thank You for your confirmation @vidhi-github

**Comment by vidhi-github** [comment]
Thanku
