### ISSUE TITLE
Ping Pong Game to be added

### ISSUE THREAD

**Issue by Abhishek2634** [divyansh-2005/GAME_PLAYER#29]
**Name of Game**
ping pong

**Description & features**
ping pong two player game so that they can play mutually.  @divyansh-2005  please assign this issue to me under gssoc  , hacktoberfest label .

**check list**
- [ ] I am contributing under GSSoC-ext
- [ ] I am contributing under hacktoberfest
- [ ] I follow contribution guidlines

**Comment by zalabhavy** [comment]
@Abhishek2634 Go ahead.
