### ISSUE TITLE
Othello

### ISSUE THREAD

**Issue by Aditijainnn** [divyansh-2005/GAME_PLAYER#307]
**Name of Game**
Othello is a strategy board game for two players, played on an 8x8 uncheckered board. 

**Description & features**
Two players—one plays black discs, and the other plays white discs.
majority of your color discs on the board when the last playable square is filled.

**Screen Shot/ Demo video**

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Comment by zalabhavy** [comment]
@Aditijainnn Without assignment you can make PRs.
