### ISSUE TITLE
Adding  description to the  games on the home screen for better user experiences 

### ISSUE THREAD

**Issue by RabdeepKaur** [divyansh-2005/GAME_PLAYER#31]
Currently, the game section on the home screen only displays the game title, without any accompanying description. This can lead to confusion, as users may not immediately understand what each game is about or how to play it. The absence of descriptions makes the games appear less engaging, which can prevent users from interacting with them. 

Current Home screen
![TeleGames - Google Chrome 10_4_2024 9_35_40 AM](https://github.com/user-attachments/assets/0bbecd65-c53c-469b-b6c6-808e810dfffb)

To improve the user experience and engagement, I propose adding creative and engaging descriptions to each game in the game section.
Home screen after description added
![TeleGames - Google Chrome 10_4_2024 9_36_46 AM](https://github.com/user-attachments/assets/010424fc-9c68-411f-bf4f-d53fbe35afdf)

Assignment Request: Please assign this issue to me, as I would like to work on implementing this enhancement.

**check list**
- [✅ ] I am contributing under GSSoC-ext
- [✅ ] I am contributing under hacktoberfest
- [✅ ] I follow contribution guidlines

**Comment by RabdeepKaur** [comment]
hey @divyansh-2005  I would like to work on this issue , so please assign it to me

**Comment by zalabhavy** [comment]
@RabdeepKaur Go ahead.
