### ISSUE TITLE
NEW GAME [ ROCKET BOOST ]

### ISSUE THREAD

**Issue by KrishChothani** [divyansh-2005/GAME_PLAYER#38]
### **Rocket Boost Game**

**Overview:**
Rocket Boost is a Unity-based game where players control a rocket that moves in a 3D environment along the x and y axes. The objective is to navigate from point \( p \) to point \( q \) while avoiding obstacles. Upon reaching point \( q \), players advance to the next level. If they hit an obstacle, they must replay the level.

**Game Mechanics:**
- **Movement:** Players control the rocket's movement along the x and y axes using keyboard.
- **Levels:** Each level requires the player to reach point \( q \) from point \( p \).
- **Obstacles:** Players encounter obstacles that, when hit, force them to restart the level.
- **Speed Boost (Proposed Feature):** 
  - Players can activate a temporary speed boost to enhance gameplay.
  - Visual effects such as a trail behind the rocket will indicate the boost.
  - A cooldown period will prevent continuous use of the boost.

**Screen Shot/ Demo Video:**
![Game Preview](https://raw.githubusercontent.com/KrishChothani/GAME_PLAYER/main/Screenshot%202024-10-04%20175131.png)

**Additional Context:**
Rocket Boost combines strategic navigation and thrilling gameplay, encouraging players to time their speed boosts effectively while avoiding obstacles. This will increase engagement and replayability as players strive to complete levels successfully.

**Check List:**
- [X] I am contributing under GSSoC-ext
- [X] I am contributing under Hacktoberfest
- [X] I follow contribution guidelines

**Comment by KrishChothani** [comment]
hey @divyansh-2005 I would like work on this,  so please assign me.

**Comment by zalabhavy** [comment]
@KrishChothani Go ahead.
