### ISSUE TITLE
To improve the overall layout of the Rock-Paper-Scissors game

### ISSUE THREAD

**Issue by RabdeepKaur** [divyansh-2005/GAME_PLAYER#44]
**Issue**
The current layout of the Rock-Paper-Scissors game has several issues that make the overall user interface (UI) feel unclean and cluttered. The positioning of key elements such as the message box, reset button, and footer needs improvement for better usability and visual clarity.
The footer is positioned too closely to the game components.This overlapping makes the UI feel cluttered and reduces the distinction between gameplay and the footer section.
The message box and reset button are not well aligned. The reset button currently sits in an awkward position, making it hard to access or notice immediately

Current layout
![Screenshot (94)](https://github.com/user-attachments/assets/fd9d7586-fd29-4905-9efc-ce7005815d93)

The solution :
Rearrange the layout so that the message box and reset button are clearly and logically positioned.
Add more spacing around the footer to separate it from the main game area, ensuring that it does not overlap or interfere with the core elements of the game.

## Layout after improvement 
![Screenshot (96)](https://github.com/user-attachments/assets/ec39fa2b-97d1-4d69-995f-1620f90a4bbb)

**check list**
- [ ✅] I am contributing under GSSoC-ext
- [ ✅] I am contributing under hacktoberfest
- [✅ ] I follow contribution guidlines

I would like to work on this issue , so  please assign this issue to me .

**Comment by RabdeepKaur** [comment]
hi @divyansh-2005  I would like to work on this issue so please assign it to me .

**Comment by zalabhavy** [comment]
@RabdeepKaur Go ahead.
