### ISSUE TITLE
EGG CATCHER

### ISSUE THREAD

**Issue by AayushiJapsare15** [divyansh-2005/GAME_PLAYER#54]
**Name of Game**
Users are looking for instant games that are easy to access and offer an engaging challenge and egg catcher is one such game. We should add such a popular, nostalgic and engaging game.

Game description:

Player is given 10 lives. The hen will move from left to right and will often lay eggs the player will have to catch them using basket without missing it.

**Description & features**
Instant Play: No download needed, just click and play.

**Screen Shot/ Demo video**
This is the game I have developed.
![image](https://github.com/user-attachments/assets/a7478e80-29a0-4dec-8ba9-abf37aa69986)

https://github.com/user-attachments/assets/8943e2a8-e176-41ed-9fde-3679a027e77f

unmute for better experience.

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Comment by AayushiJapsare15** [comment]
@divyansh-2005 can you please assign me this issue.

**Comment by AayushiJapsare15** [comment]
I have started working on it. 
Would like you to please add 'hacktoberfest-accepted' label as well since it is crucial for hacktober .

**Comment by AayushiJapsare15** [comment]
Whom to ask doubts during development and how

**Comment by AayushiJapsare15** [comment]
I am not able it is asking for premium

**Comment by zalabhavy** [comment]
@AayushiJapsare15 I sent you a connection request on LinkedIn through the link on your GitHub profile.
