### ISSUE TITLE
[BUG] Font size very small in Guess the Hex, Flip card game and snake games

### ISSUE THREAD

**Issue by govindumeesala** [divyansh-2005/GAME_PLAYER#61]
**Describe the bug**
Font size very small in Guess the Hex, Flip card game and snake, which is not user friendly 

**To Reproduce**
1. Go to Guess the Hex, Flip card game and snake games 
2. Font size is very small there in the games

**Expected behavior**
Text should be readable

**Screenshots before**
![image](https://github.com/user-attachments/assets/cb53654c-15e7-48ca-b3d1-ad16add2804a)

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

@zalabhavy  I will work on it

**Comment by zalabhavy** [comment]
Fixed
