### ISSUE TITLE
[BUG] Navbar and footer not taking up entire width

### ISSUE THREAD

**Issue by govindumeesala** [divyansh-2005/GAME_PLAYER#63]
**Describe the bug**
Navbar and footer not taking up entire width. It does not provide good user experience.

**To Reproduce**
1. Go to website
2. See navbar and footer not taking up entire width

**Expected behavior**
they should take up entire width

**Screenshots before**
![image](https://github.com/user-attachments/assets/a1ef2607-9478-497b-9b04-b06a74c683a9)

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

@zalabhavy  I would like to work on it

**Comment by zalabhavy** [comment]
Fixed
