### ISSUE TITLE
new_game: Snake Game 

### ISSUE THREAD

**Issue by Abhishek2634** [divyansh-2005/GAME_PLAYER#64]
**Name of Game**
Snake Game

**Description & features**
snake which grows as he eats the squares. player can see his high score as well.

**check list**
- [ ] I am contributing under GSSoC-ext
- [ ] I am contributing under hacktoberfest
- [ ] I follow contribution guidlines

**Comment by Abhishek2634** [comment]
@divyansh-2005  assign this issue to me

**Comment by zalabhavy** [comment]
@Abhishek2634 Go ahead.

**Comment by zalabhavy** [comment]
@Abhishek2634 sorry this is already present.
