### ISSUE TITLE
[BUG]Some of the content hides behind the sticky navigation bar

### ISSUE THREAD

**Issue by Shreya-1305** [divyansh-2005/GAME_PLAYER#88]
**Describe the bug**
Content hides behind the navigation bar

**To Reproduce**
1. Go to Emoji Intruder
2. Click on play

**Expected behavior**
Content should be below the navigation bar and not behind the navigation bar.

**Screenshots before**
![image](https://github.com/user-attachments/assets/9f21259d-0b5e-4983-b024-695f74261057)

**Screenshots Ater**
![image](https://github.com/user-attachments/assets/837b2d29-2227-4c78-b859-487af78e4168)

Please assign me this issue so that I can work on this issue.

**check list**
- ✅ I am contributing under GSSoC-ext
- ✅I am contributing under hacktoberfest
- ✅ I follow contribution guidlines

**Comment by Shreya-1305** [comment]
@divyansh-2005 please assign this issue to me

**Comment by Shreya-1305** [comment]
@zalabhavy Please asssign this issue to me

**Comment by zalabhavy** [comment]
@Shreya-1305 It is solved update your repository find another issue.
