### ISSUE TITLE
[BUG]React app not running due to bug in app.jsx

### ISSUE THREAD

**Issue by Shreya-1305** [divyansh-2005/GAME_PLAYER#89]
**Describe the bug**
React app not running as path mentioned for the tetris game is incorrect. 

**To Reproduce**
1. Go to Games in Myproject
2. run command  npm run dev

**Expected behavior**
App should open without error 

**Screenshots before**
![image](https://github.com/user-attachments/assets/0229492e-1da3-4ff8-94a4-df210d01a9c5)

Path for Tetris game is incorrect
![image](https://github.com/user-attachments/assets/e57f4b6f-a0aa-41a1-b1ba-4b2073a4f808)

**screenshots after fix***
![image](https://github.com/user-attachments/assets/95c91047-41be-4bd8-b421-8983f0b49e9e)
![image](https://github.com/user-attachments/assets/3346dd0e-9a88-46b3-8b04-e4a61ec3ecf3)

**check list**
- ✅ I am contributing under GSSoC-ext
- ✅ I am contributing under hacktoberfest
- ✅ I follow contribution guidlines

Please assign me this issue. I want to work on this issue.

**Comment by Shreya-1305** [comment]
@divyansh-2005 please assign this issue to me

**Comment by Shreya-1305** [comment]
@zalabhavy Please asssign this issue to me

**Comment by zalabhavy** [comment]
@Shreya-1305 Solved.
