### ISSUE TITLE
[FEATURE] Adding social media links to the future to make it more attractive.

### ISSUE THREAD

**Issue by tarunkumar2005** [divyansh-2005/GAME_PLAYER#96]
**Is your feature request related to a problem? Please describe.**
[FEATURE] Adding social media links to the future to make it more attractive.

**Describe the solution you'd like**
i will include all popular social media links in the footer for easy access and contacting the website owner or team.

**check list**
- [X] I am contributing under GSSoC-ext
- [X] I am contributing under hacktoberfest
- [X] I follow contribution guidlines

Assign this to me under gssoc 2024 ext and hacktoberfest i would like to work on this issue.

**Comment by Abusha-Ansari** [comment]
i will include all popular social media links in the footer for easy access and contacting the website owner or team.

**check list**
 I am contributing under hacktoberfest
 I follow contribution guidlines

Assign this to me under hacktoberfest i would like to work on this issue.

**Comment by zalabhavy** [comment]
Now not needed.
